# Build image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS builder
WORKDIR /app

  # Copy files
COPY . ./

RUN dotnet restore
RUN dotnet build -c Release --no-restorer


RUN dotnet publish -c Release --no-build -o out

  # Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine
WORKDIR /app
COPY --from=builder /app/out .
ENV ASPNETCORE_URLS="http://*:5000"
ENTRYPOINT ["dotnet", "DockerContainerRegistry.dll"]
