# Build image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS builder
WORKDIR /app

  # Copy files
COPY . ./

RUN dotnet restore
RUN dotnet build -c Release --no-restore


RUN dotnet publish -c Release --no-build -o out

  # Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=builder /app/out .
ENV ASPNETCORE_URLS="http://*:5000"
ENTRYPOINT ["dotnet", "AzureContainerRegistry.dll"]
